version: 0.2

phases:
  pre_build:
    commands:
      - pwd
      - curl -L https://dl.dagger.io/dagger/install.sh | sh
      - ls
      - ./bin/dagger version
  build:
    commands:
      - ./bin/dagger project init
      - ./bin/dagger project update
      - ./bin/dagger do build
