version: 0.2

phases:
  pre_build:
    commands:
      - curl -L https://dl.dagger.io/dagger/install.sh | sh
      - ./bin/dagger version
  build:
    commands:
      - ./bin/dagger project init
      - ./bin/dagger project update github.com/smrz2001/pipelinetools@main
      - ./bin/dagger do push -p cue.mod/pkg/github.com/smrz2001/pipelinetools/ceramic/ci.cue
